database:
  read:
    host: 127.0.0.1
    username: "default"
    password: "root"
    port: 3306
    dbname: "default"
  write:
    host: 127.0.0.1
    username: "default"
    password: "root"
    port: 3306
    dbname: "default"